week 3 additional features
biancamacias/step-2020 pull request #15
Opened 2020-07-10 19:17 UTC by biancamacias

this pull request is to add an ```<input>``` element that submits a ```POST``` request to the new /delete-data handler. i left a to-do in the DeleteServlet.java file because im not sure how to get the comments into that servlet so they can be deleted. most of the examples ive seen online create and delete the entities in the same doPost function or just show a single line of code with no context. 

in the earlier commits, i also added a feature that limits the amount of comments that are added to the page with a hard-coded value.

2020-07-10 22:20 UTC, ccondit requested changes

2020-07-10 22:20 UTC, ccondit commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +      List<Entity> limitedResults = results.asList(FetchOptions.Builder.withLimit(2));
Can you leave this change for a separate PR? Let's focus on the delete in this PR...

2020-07-10 22:20 UTC, ccondit commented on portfolio/src/main/java/com/google/sps/servlets/DeleteServlet.java
> +        // TO DO: add data structure of keys and add while loop that deletes keys from that data structure
Couple of things here:

- Have a read through http://cloud/appengine/docs/standard/java/datastore/creating-entities#Deleting_entities which should help with deleting entities.
- This isn't in the public java style guide, but let's format TODOs with a common style:
  -   // TODO(username): do something
  -   // TODO(#issueNumber): do something (prefer this style)

2020-07-11 03:02 UTC, kaveh096 commented
> this pull request is to add an `<input>` element that submits a `POST` request to the new /delete-data handler. i left a to-do in the DeleteServlet.java file because im not sure how to get the comments into that servlet so they can be deleted. most of the examples ive seen online create and delete the entities in the same doPost function or just show a single line of code with no context.
> 
> in the earlier commits, i also added a feature that limits the amount of comments that are added to the page with a hard-coded value.

Are you trying to delete all comment, or a specific comment that the user selected?

2020-07-13 17:27 UTC, biancamacias commented
> > this pull request is to add an `<input>` element that submits a `POST` request to the new /delete-data handler. i left a to-do in the DeleteServlet.java file because im not sure how to get the comments into that servlet so they can be deleted. most of the examples ive seen online create and delete the entities in the same doPost function or just show a single line of code with no context.
> > in the earlier commits, i also added a feature that limits the amount of comments that are added to the page with a hard-coded value.
> 
> Are you trying to delete all comments, or a specific comment that the user selected?

i would lie to just delete all the comments

2020-07-15 01:24 UTC, kaveh096 approved these changes

2020-07-15 01:24 UTC, kaveh096 commented on portfolio/src/main/java/com/google/sps/servlets/DeleteServlet.java
> +        // TO DO(biancamacias): add data structure of keys and add while loop that deletes keys from that data structure
```suggestion
        // TODO(biancamacias): add data structure of keys and add while loop that deletes keys from that data structure
```

2020-07-22 19:04 UTC, merged